# Generated by Django 5.0.4 on 2024-04-04 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersModel',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('matches_played', models.IntegerField()),
                ('average', models.FloatField()),
                ('strike_rate', models.FloatField()),
            ],
        ),
    ]
