# Generated by Django 5.0.4 on 2024-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmodel',
            name='player_role',
            field=models.CharField(default='batsman', max_length=100),
        ),
    ]
