# Generated by Django 5.0.4 on 2024-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTable',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('squad', models.JSONField()),
            ],
        ),
    ]
