# Generated by Django 5.0.4 on 2024-04-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='squad',
            field=models.JSONField(default=dict),
        ),
    ]
