# Generated by Django 5.0.4 on 2024-04-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_matchtable_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='squad',
            field=models.JSONField(null=True),
        ),
    ]
