# Generated by Django 5.0.4 on 2024-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_matchtable_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersSquadTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('player_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchtable',
            name='squad',
        ),
    ]
